services:
  php:
    build:
      context: .
    container_name: mini-framework-php
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    container_name: mini-framework-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./systems/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
